version: '2'

services:
  bit-node:
    build:
      context: .
      dockerfile: ./containers/bitcoin/node/Dockerfile
      args:
        - RPC_USER=$RPC_USER
        - RPC_AUTH=$RPC_AUTH
        - RPC_PASSWORD=$RPC_PASSWORD
        - BITCOIND_VERSION=$BITCOIND_VERSION
        - RPC_BIND=$RPC_BIND
        - RPC_ALLOWIP=$RPC_ALLOWIP
    volumes:
      - ./containers/bitcoin/node/data:/root/.bitcoin
    mem_limit: 15gb
    ports:
      - "8332:8333"
      - "18332:18332"
    stdin_open: true
    tty: true
    networks:
      bitcoind-net:
        ipv4_address: $RPC_BIND

  bit-client:
    build:
      context: .
      dockerfile: ./containers/bitcoin/client/Dockerfile
      args:
        - RPC_USER=$RPC_USER
        - RPC_AUTH=$RPC_AUTH
        - RPC_PASSWORD=$RPC_PASSWORD
        - BITCOIND_VERSION=$BITCOIND_VERSION
        - RPC_BIND=$RPC_BIND
        - RPC_ALLOWIP=$RPC_ALLOWIP
    volumes:
      - ./containers/bitcoin/client/data:/root/.bitcoin
    mem_limit: 10gb
    links:
      - bit-node
    ports:
      - "3333:3333"
    stdin_open: true
    tty: true
    networks:
      bitcoind-net:
        ipv4_address: $IP_FOR_BITCOIN_CLIENT

  app-base:
    build:
      context: .
      dockerfile: containers/app/base/Dockerfile
    working_dir: /go/src/github.com/KoganezawaRyouta/bitcoind-test
    volumes:
      - .:/go/src/github.com/KoganezawaRyouta/bitcoind-test

#  grpc-server:
#    extends: app-base
#    command: >-
#      sh -c "
#        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin grpc_server'
#      "
#    stdin_open: true
#    tty: true
#    ports:
#      - "2222:2222"
#
#  grpc-client:
#    extends: app-base
#    command: >-
#      sh -c "
#        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin grpc_client_list'
#      "
#    stdin_open: true
#    tty: true
#    links:
#      - grpc-server

  nuts-sub:
    extends: app-base
    command: >-
      sh -c "
        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin subscriber'
      "
    stdin_open: true
    tty: true
    links:
      - nuts-server

  nuts-pub:
    extends: app-base
    command: >-
      sh -c "
        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin publisher'
      "
    stdin_open: true
    tty: true
    links:
      - nuts-server
    networks:
      bitcoind-net:
        ipv4_address: $IP_FOR_NUTS_PUB

  nuts-server:
    extends: app-base
    command: gnatsd -D -V -a $IP_FOR_NUTS_SERVER -p $PORT_FOR_NUTS_SERVER
    ports:
      - "4222:4222"
    stdin_open: true
    tty: true
    networks:
      bitcoind-net:
        ipv4_address: $IP_FOR_NUTS_SERVER

networks:
  bitcoind-net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.176.2/24
         gateway: 192.168.176.1
