version: '2'

services:
  node:
    build:
      context: .
      dockerfile: ./containers/bitcoin/node/Dockerfile
      args:
        - RPC_USER=$RPC_USER
        - RPC_AUTH=$RPC_AUTH
        - RPC_PASSWORD=$RPC_PASSWORD
        - BITCOIND_VERSION=$BITCOIND_VERSION
        - RPC_BIND=$RPC_BIND
        - RPC_ALLOWIP=$RPC_ALLOWIP
    volumes:
      - ./containers/bitcoin/node/data:/root/.bitcoin
    mem_limit: 15gb
    ports:
      - "8332:8333"
      - "18332:18332"
    stdin_open: true
    tty: true
    networks:
      bitcoind-net:
        ipv4_address: $RPC_BIND

  client:
    build:
      context: .
      dockerfile: ./containers/bitcoin/client/Dockerfile
      args:
        - RPC_USER=$RPC_USER
        - RPC_AUTH=$RPC_AUTH
        - RPC_PASSWORD=$RPC_PASSWORD
        - BITCOIND_VERSION=$BITCOIND_VERSION
        - RPC_BIND=$RPC_BIND
        - RPC_ALLOWIP=$RPC_ALLOWIP
    volumes:
      - ./containers/bitcoin/client/data:/root/.bitcoin
    mem_limit: 10gb
    links:
      - node
    ports:
      - "3333:3333"
    stdin_open: true
    tty: true
    networks:
      bitcoind-net:
        ipv4_address: $RPC_ALLOWIP

  grpc-base:
    build:
      context: .
      dockerfile: ./containers/grpc/base/Dockerfile
    working_dir: /go/src/github.com/KoganezawaRyouta/bitcoind-test
    volumes:
    - .:/go/src/github.com/KoganezawaRyouta/bitcoind-test

  grpc-server:
    extends: grpc-base
    command: >-
      sh -c "
        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin grpc_server'
      "
    stdin_open: true
    tty: true
    ports:
      - "2222:2222"

  grpc-client-list:
    extends: grpc-base
    command: >-
      sh -c "
        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin grpc_client_list'
      "
    stdin_open: true
    tty: true
    links:
      - grpc-server

  grpc-client-add:
    extends: grpc-base
    command: >-
      sh -c "
        reflex -s -r '\\.go$$' -R '^vendor/' -- sh -c 'make build && ./bin/grpc-bitcoin grpc_client_add'
      "
    stdin_open: true
    tty: true
    links:
    - grpc-server

networks:
  bitcoind-net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.176.2/24
         gateway: 192.168.176.1
